version: '3.9'

# Build the fastapi server and expose on port 8000
services:
  fastapi:
    build: .
    platform: "linux/amd64"
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - app

networks:
  app:
