name: '🧪 Run unit tests'

permissions:
  contents: read

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened]
  push:
    branches:
      - main

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b

      - name: 'Install Python3'
        uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d
        with:
          python-version: '3.12.3'

      - name: 'Install dependencies'
        run: |
          python3 -m pip install --upgrade pip
          pip3 install wheel
          pip3 install --no-build-isolation -r requirements.txt
          pip3 install pytest

      - name: 'Run tests with pytest'
        run: pytest tests/unit
